name: Deploy
on:
  push:
    branches: [ public-package ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Prerequisites
        run: sudo apt-get -y install libpng-dev libimagequant-dev
      - run: npm ci
      - name: Verify
        run: npm test
        env:
          CI: true
      - name: Publish
        if: ${{ success() }}
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  